config/routes.rb
Rails.application.routes.draw do
  get 'public/orders'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  scope module: :public do   
    get '/customers/mypage' => "customers#show"
    get '/customers/mypage/edit' => "customers#edit"
    patch '/customers/withdraw'=>"customers#withdraw" 
    patch '/customers/mypage' => "customers#update"
    get '/customers/confirmation'=>"customers#confirmation"  
    delete '/cart_items/destroy_all'=>"cart_items#destroy_all", as: 'destroy_all'
    get   '/orders/completion'=>"orders#completion"
    post  '/orders/confirmation'=>"orders#confirmation"
   
    resources :homes
    resources :items
    resources :registrations
    resources :cart_items
    resources :orders
    resources :addresses
    root to: "homes#top"
  get '/about'=>"homes#about"

end
    namespace :admin do
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :orders_details
   root "homes#top"
  
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
    end
 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :addresses
has_many :cart_items 
has_many :orders
def address_display
  '〒' + postal_code + ' ' + address + ' ' + first_name + ' ' + last_name
    end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
      has_one_attached :image
      has_many :order_products
      has_many :cart_items 
      belongs_to :genre
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_products
    has_many :items,through: :order_products
   enum payment_method: {credit_card: 0, transfer: 1} 
    def order_address
    '〒' + postal_code + '\n' + address + '\n' + name
    end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
def index
    @customers = Customer.page(params[:page])
end
def show
    @customer = Customer.find(params[:id])
end
def edit
        @customer = Customer.find(params[:id])
end
def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to  admin_customer_path(params[:id])
end
private
def customer_params
    params.require(:customer).permit(:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:is_active,:telephone_number)
end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    before_action :authenticate_admin!
    def index
        @genres = Genre.all
    end    
    def create
        genre = Genre.new(genre_params)
        genre.save
        redirect_to '/admin/genres'
    end
    def edit
        @genre = Genre.find(params[:id])
    end
    def update
        genre = Genre.find(params[:id])
        genre.update(genre_params)
        redirect_to '/admin/genres'
    end
    def genre_params
        params.require(:genre).permit(:name)
    end    
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!
    def top
        @order = Order.page(params[:page]).per(10)
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!
def new
    @item = Item.new
    @genres = Genre.all
end
def create
    item = Item.new(item_params)
    item.save
    redirect_to '/admin/items'
end
def index
    @items = Item.page(params[:page]).per(10)
end
def show
    @item = Item.find(params[:id])
end
def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
end
      private
  def item_params
    params.require(:item).permit(:genre_id, :name, :image,:introductiion,:is_active,:price)  
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :authenticate_admin!
    def new
        @order = current_customer
    end
    def show
 @order = Order.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?
def after_sign_in_path_for(resource)
  case resource
  when Admin
  admin_root_path
  
  when Customer
    root_path
  end
end

# def after_sign_out_path_for(resource)
#   case resource
#   when :admin
#     new_admin_session_path
#     end
  
# end

protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])

  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/customers/edit.html.erb
<h1><%= @customer.last_name+@customer.first_name %>さんの会員情報編集</h1>
<%= form_with model: @customer, url:admin_customer_path, method: :patch do |customer|%>
<table>
  <thead>
    <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
    </tr>
    <tr>
        <th>氏名</th>
        <td><%= customer.text_field :last_name %></td>
        <td><%= customer.text_field :first_name %></td>
        </tr>
        <tr>
             <th>フリガナ</th>
             <td><%= customer.text_field :last_name_kana %></td>
             <td><%= customer.text_field :first_name_kana %></td>
        </tr>
          <tr>
                <th>郵便番号</th>
                <td><%= customer.text_field  :postal_code %></td>
          </tr>
        <tr>
            <th>住所</th>
            <td><%= customer.text_field :address %></td>
            </tr>
          <tr>  
          <th>電話番号</th>
          <td><%= customer.text_field :telephone_number %></td>
          </tr>
        <tr>
               <th>メールアドレス</th>
               <td><%= customer.text_field :email %></td>
        </tr>
      <tr>
      <th>会員ステータス</th>
      <td><%= customer.radio_button :is_active, true %>有効</td>
      <td><%= customer.radio_button :is_active, false %>退会</td>
      </tr>
      </table>
       <%= customer.submit '変更を保存', class:  "btn btn-success" %>
      <% end %>

app/views/admin/customers/index.html.erb
<h1>会員一覧</h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="bg-light">会員ID</th>
      <th class="bg-light">氏名</th>
      <th class="bg-light">メールアドレス</th>
      <th class="bg-light">ステータス</th>
    </tr>
  </thead>
  <tbody>
      <% @customers.each do |customer|%>
    <tr>
      <td><%= customer.id%></td>
      <td> <%= link_to admin_customer_path(customer.id) do %>
     <%= customer.last_name+customer.first_name %>
        <% end %>
     </td>
   
      <td><%= customer.email%></td>
      <% if customer.is_active ==true %>
       <td>有効</td>
      <% else %>
      <td>退会</td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<h1><%= @customer.last_name+@customer.first_name %>さんの会員詳細</h1>
<table>
  <thead>
    <tr>
    
        <th>会員ID</th>
        <td><%= @customer.id%></td>
    </tr>
    <tr>
        <th>氏名</th>
        <td><%= @customer.last_name+@customer.first_name %></td>
        </tr>
        <tr>
             <th>フリガナ</th>
             <td><%= @customer.last_name_kana+@customer.first_name_kana%></td>
        </tr>
          <tr>
                <th>郵便番号</th>
                <td><%= '〒'+@customer.postal_code%></td>
          </tr>
        <tr>
            <th>住所</th>
            <td><%= @customer.address%></td>
            </tr>
          <tr>  
          <th>電話番号</th>
          <td><%= @customer.telephone_number%></td>
          </tr>
        <tr>
               <th>メールアドレス</th>
               <td><%= @customer.email%></td>
        </tr>
      <tr>
              <th>会員ステータス</th>
              <% if @customer.is_active == true%>
              <td>有効</td>
              <% else %>
                <td>退会</td>
                <% end %>
      </tr>
  </thead>
</table>
<%= link_to '編集する', edit_admin_customer_path(params[:id]) ,class: "btn btn-success" %>
<%= link_to'注文履歴一覧を見る',  admin_order_path(params[:id]),class: "btn btn-primary" %>