config/routes.rb
Rails.application.routes.draw do
  get 'public/orders'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  scope module: :public do   
    get '/customers/mypage' => "customers#show"
    get '/customers/mypage/edit' => "customers#edit"
    patch '/customers/withdraw'=>"customers#withdraw" 
    patch '/customers/mypage' => "customers#update"
    get '/customers/confirmation'=>"customers#confirmation"  
    delete '/cart_items/destroy_all'=>"cart_items#destroy_all", as: 'destroy_all'
    get   '/orders/completion'=>"orders#completion"
    post  '/orders/confirmation'=>"orders#confirmation"
   
    resources :homes
    resources :items
    resources :registrations
    resources :cart_items
    resources :orders
    resources :addresses
    root to: "homes#top"
  get '/about'=>"homes#about"

end
    namespace :admin do
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :orders_details
   root "homes#top"
  
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
    end
 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :addresses
has_many :cart_items 
has_many :orders
def address_display
  '〒' + postal_code + ' ' + address + ' ' + first_name + ' ' + last_name
    end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
      has_one_attached :image
      has_many :order_products
      has_many :cart_items 
      belongs_to :genre
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_products
    has_many :items,through: :order_products
   enum payment_method: {credit_card: 0, transfer: 1} 
    def order_address
    '〒' + postal_code + '\n' + address + '\n' + name
    end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    before_action :authenticate_admin!
    def index
        @genres = Genre.all
    end    
    def create
        genre = Genre.new(genre_params)
        genre.save
        redirect_to '/admin/genres'
    end
    def edit
        @genre = Genre.find(params[:id])
    end
    def update
        genre = Genre.find(params[:id])
        genre.update(genre_params)
        redirect_to '/admin/genres'
    end
    def genre_params
        params.require(:genre).permit(:name)
    end    
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!
    def top
        @order = Order.page(params[:page]).per(10)
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!
def new
    @item = Item.new
    @genres = Genre.all
end
def create
    item = Item.new(item_params)
    item.save
    redirect_to '/admin/items'
end
def index
    @items = Item.page(params[:page]).per(10)
end
def show
    @item = Item.find(params[:id])
end
def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
end
      private
  def item_params
    params.require(:item).permit(:genre_id, :name, :image,:introductiion,:is_active,:price)  
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :authenticate_admin!
    def new
        @order = current_customer
    end
    def show
 @order = Order.find(params[:id])
    end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  before_action :authenticate_admin!
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?
def after_sign_in_path_for(resource)
  case resource
  when Admin
  admin_root_path
  
  when Customer
    root_path
  end
end

# def after_sign_out_path_for(resource)
#   case resource
#   when :admin
#     new_admin_session_path
#     end
  
# end

protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])

  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/genres/edit.html.erb
<h2 class= "bg-light">ジャンル編集</h2>
<%= form_with model: @genre, url:admin_genre_path, method: :patch do |f| %>
<table>
  <thead>
    <tr>
      <th>ジャンル名</th>
      <th><%= f.text_field :name %></th>
      <th><%= f.submit '変更を保存', class: "btn btn-success" %></th>
      <% end %>
    </tr>
  </thead>
 </table>

app/views/admin/genres/index.html.erb
<h2 class= "bg-light">ジャンル一覧・追加</h2>
<%= form_with model: Genre.new, url:admin_genres_path do |f| %>
<table>
  <thead>
    <tr>
      <th>ジャンル名</th>
      <th><%= f.text_field :name %></th>
      <th><%= f.submit '新規登録', class: "btn btn-success" %></th>
      <% end %>
    </tr>
  </thead>
 </table>


<div>ジャンル</div>
<% @genres.each do |genre| %>



<table>
  <thead>
    <tr>
      <th class= "bg-light">ジャンル</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= genre.name  %></td>
      <td><%=link_to '編集する', edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
      <% end %>
    </tr>
 </tbody>
</table>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>
<%= form_with model: @item, url:admin_item_path(params[:id]), method: :patch do |f| %>
<div>商品画像</div><%= f.file_field :image, accept: "image/*" %></br>
<div>商品名</div><%= f.text_field :name  %></br>
<div>商品説明</div><%= f.text_area :introductiion %></br>
<div>ジャンル</div><%= f.collection_select :genre_id, @genres, :id, :name %></br>
<div>税抜き価格</div><%= f.text_field :price %><div>円</div></br>
<div>販売ステータス</div><%= f.radio_button :is_active, true %><div>販売中</div>
<%= f.radio_button :is_active, false %><div>販売停止中</div></br>
<%= f.submit '変更を保存',class: "btn btn-success" %>

<% end %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>
<%= link_to new_admin_item_path do %>
<i class="fa-solid fa-plus"></i>
<% end %>
<table class="table table-bordered">
  <thead>
    <tr>
    <th class= "bg-light">商品ID</th>
    <th class= "bg-light">商品名</th>
    <th class= "bg-light">税抜価格</th>
    <th class= "bg-light">ジャンル</th>
    <th class= "bg-light">ステータス</th>
    </tr>
    </thead>
    <tbody>
      <% @items.each do |item|%>
        <tr>
            <td><%= item.id %></td>
            <td><%= link_to admin_item_path(item.id) do %>
              <%= item.name %>  
              <% end %></td>
            <td><%= item.price%></td>
            <td><%= item.genre.name%></td>
            <% if item.is_active ==true %>
       <td>販売中</td>
      <% else %>
      <td>販売停止中</td>
      <% end %>
        </tr>
        <% end %>
        <%= paginate @items %>
    </tbody>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>
<%= form_with model: @item, url:admin_items_path do |f| %>
<div>商品画像</div><%= f.file_field :image, accept: "image/*" %></br>
<div>商品名</div><%= f.text_field :name, placeholder: "商品名" %></br>
<div>商品説明</div><%= f.text_area :introductiion, placeholder: "ここに説明文を記述します。" %></br>
<div>ジャンル</div><%= f.collection_select :genre_id, @genres, :id, :name %></br>
<div>税抜き価格</div><%= f.text_field :price, placeholder: "1000" %><div>円</div></br>
<div>販売ステータス</div><%= f.radio_button :is_active, true %><div>販売中</div>
<%= f.radio_button :is_active, false %><div>販売停止中</div></br>
<%= f.submit '新規登録',class: "btn btn-success" %>

<% end %>

app/views/admin/items/show.html.erb
<h1>商品の詳細</h1>
<%= image_tag @item.image %>
<table>
    <thead>
        <tr>
            <th>商品名</th>
            <td><%=@item.name %></td>
        </tr>
         <tr>
            <th>商品説明</th>
            <td><%= @item.introductiion %></td>
        </tr>
         <tr>
            <th>ジャンル</th>
            <td><%= @item.genre.name%></td>
        </tr>
         <tr>
            <th>税込価格</br>
            （税抜価格）</th>
            <td><%=@item.price*1.1%></br>
            <%=@item.price%></td>
        </tr>
        
    </thead>
</table>
<%=link_to '編集する',edit_admin_item_path(params[:id]) %>

app/views/admin/orders/show.html.erb
<h1>注文履歴詳細</h1>
<table>
    <tr>
        <th>購入者</th>
            <td><%= @order.name%></td>
        
    </tr>
     <tr>
        <th>注文日</th>
            <td><%= @order.created_at%></td>
        
    </tr>
     <tr>
        <th>配送先</th>
            <td><%= '〒'+@order.postal_code+@order.address+@order.name%></td>
        
    </tr>
     <tr>
        <th>支払方法</th>
            <td><%=@order.payment_method%></td>
        
    </tr>
</table>
<table class="table table-bordered">
    <tr>
        <th class= "bg-light">商品名</th>
        <th class= "bg-light">単価（税抜）</th>
        <th class= "bg-light">数量</th>
        <th class= "bg-light">小計</th>
        </tr>
              <% @order.order_products.each do |order| %>
        <tr>
            <td><%= order.item.name %></td>
             <td><%= order.price*1.1%></td>
              <td><%=order.amount%></td>
               <td><%= order.price*1.1*order.amount %></td>
               
        </tr>
        <% end %>
        </table>
        <table>
            <tr>
                <th>商品合計</th>
                <td><%=@order.payment_amount%></td>
            </tr>
              <tr>
                <th>送料</th>
                <td>800円</td>
            </tr>
              <tr>
                <th>請求金額合計</th>
                <td><%= @order.payment_amount+800%></td>
            </tr>
        </table>