config/routes.rb
Rails.application.routes.draw do
  get 'public/orders'
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  scope module: :public do   
    get '/customers/mypage' => "customers#show"
    get '/customers/mypage/edit' => "customers#edit"
    patch '/customers/withdraw'=>"customers#withdraw" 
    patch '/customers/mypage' => "customers#update"
    get '/customers/confirmation'=>"customers#confirmation"  
    delete '/cart_items/destroy_all'=>"cart_items#destroy_all", as: 'destroy_all'
    get   '/orders/completion'=>"orders#completion"
    post  '/orders/confirmation'=>"orders#confirmation"
   
    resources :homes
    resources :items
    resources :registrations
    resources :cart_items
    resources :orders
    resources :addresses
    root to: "homes#top"
  get '/about'=>"homes#about"

end
    namespace :admin do
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :orders_details
   root "homes#top"
  
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
    end
 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :addresses
has_many :cart_items 
has_many :orders
def address_display
  '〒' + postal_code + ' ' + address + ' ' + first_name + ' ' + last_name
    end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
      has_one_attached :image
      has_many :order_products
      has_many :cart_items 
      belongs_to :genre
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_products
    has_many :items,through: :order_products
   enum payment_method: {credit_card: 0, transfer: 1} 
    def order_address
    '〒' + postal_code + '\n' + address + '\n' + name
    end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!
    def top
        @order = Order.page(params[:page]).per(10)
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!
def new
    @item = Item.new
    @genres = Genre.all
end
def create
    item = Item.new(item_params)
    item.save
    redirect_to '/admin/items'
end
def index
    @items = Item.page(params[:page]).per(10)
end
def show
    @item = Item.find(params[:id])
end
def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
end
      private
  def item_params
    params.require(:item).permit(:genre_id, :name, :image,:introductiion,:is_active,:price)  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?
def after_sign_in_path_for(resource)
  case resource
  when Admin
  admin_root_path
  
  when Customer
    root_path
  end
end

# def after_sign_out_path_for(resource)
#   case resource
#   when :admin
#     new_admin_session_path
#     end
  
# end

protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])

  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <% if customer_signed_in? %>
     <%= link_to "マイページ", customers_mypage_path %>
    　  <%= link_to "商品一覧",items_path %>
       <%= link_to "カート", cart_items_path %>
       <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %> 
     <% elsif admin_signed_in? %>
        <%= link_to "商品一覧", admin_items_path%>
　     <%= link_to "会員一覧",admin_customers_path %>
       <%= link_to "注文履歴一覧", admin_root_path %>
       <%= link_to "ジャンル一覧", admin_genres_path %> 
       <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %> 
     <% else %>
      <%= link_to "About", about_path %>
    　<%= link_to "商品一覧",items_path %>
     <%= link_to "新規登録", new_customer_registration_path %>
     <%= link_to "ログイン", new_customer_session_path %> 
       
     <% end %>
    </header>
    <%= yield %>
  </body>
</html>